// Generated by gencpp from file pacmod_msgs/HeadlightAuxRpt.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_HEADLIGHTAUXRPT_H
#define PACMOD_MSGS_MESSAGE_HEADLIGHTAUXRPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pacmod_msgs
{
template <class ContainerAllocator>
struct HeadlightAuxRpt_
{
  typedef HeadlightAuxRpt_<ContainerAllocator> Type;

  HeadlightAuxRpt_()
    : header()
    , headlights_on(false)
    , headlights_on_is_valid(false)
    , headlights_on_bright(false)
    , headlights_on_bright_is_valid(false)
    , fog_lights_on(false)
    , fog_lights_on_is_valid(false)
    , headlights_mode(0)
    , headlights_mode_is_valid(false)  {
    }
  HeadlightAuxRpt_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , headlights_on(false)
    , headlights_on_is_valid(false)
    , headlights_on_bright(false)
    , headlights_on_bright_is_valid(false)
    , fog_lights_on(false)
    , fog_lights_on_is_valid(false)
    , headlights_mode(0)
    , headlights_mode_is_valid(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _headlights_on_type;
  _headlights_on_type headlights_on;

   typedef uint8_t _headlights_on_is_valid_type;
  _headlights_on_is_valid_type headlights_on_is_valid;

   typedef uint8_t _headlights_on_bright_type;
  _headlights_on_bright_type headlights_on_bright;

   typedef uint8_t _headlights_on_bright_is_valid_type;
  _headlights_on_bright_is_valid_type headlights_on_bright_is_valid;

   typedef uint8_t _fog_lights_on_type;
  _fog_lights_on_type fog_lights_on;

   typedef uint8_t _fog_lights_on_is_valid_type;
  _fog_lights_on_is_valid_type fog_lights_on_is_valid;

   typedef uint8_t _headlights_mode_type;
  _headlights_mode_type headlights_mode;

   typedef uint8_t _headlights_mode_is_valid_type;
  _headlights_mode_is_valid_type headlights_mode_is_valid;



  enum {
    HEADLIGHTS_OFF = 0u,
    HEADLIGHTS_PARKING = 1u,
    HEADLIGHTS_MANUAL = 2u,
    HEADLIGHTS_AUTO = 3u,
  };


  typedef boost::shared_ptr< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> const> ConstPtr;

}; // struct HeadlightAuxRpt_

typedef ::pacmod_msgs::HeadlightAuxRpt_<std::allocator<void> > HeadlightAuxRpt;

typedef boost::shared_ptr< ::pacmod_msgs::HeadlightAuxRpt > HeadlightAuxRptPtr;
typedef boost::shared_ptr< ::pacmod_msgs::HeadlightAuxRpt const> HeadlightAuxRptConstPtr;

// constants requiring out of line definition

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pacmod_msgs': ['/tmp/binarydeb/ros-kinetic-pacmod-msgs-3.0.1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "512cf6494650979b84da331a515edaf9";
  }

  static const char* value(const ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x512cf6494650979bULL;
  static const uint64_t static_value2 = 0x84da331a515edaf9ULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/HeadlightAuxRpt";
  }

  static const char* value(const ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
bool headlights_on\n\
bool headlights_on_is_valid\n\
bool headlights_on_bright\n\
bool headlights_on_bright_is_valid\n\
bool fog_lights_on\n\
bool fog_lights_on_is_valid\n\
uint8 headlights_mode\n\
bool headlights_mode_is_valid\n\
\n\
uint8 HEADLIGHTS_OFF = 0\n\
uint8 HEADLIGHTS_PARKING = 1\n\
uint8 HEADLIGHTS_MANUAL = 2\n\
uint8 HEADLIGHTS_AUTO = 3\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.headlights_on);
      stream.next(m.headlights_on_is_valid);
      stream.next(m.headlights_on_bright);
      stream.next(m.headlights_on_bright_is_valid);
      stream.next(m.fog_lights_on);
      stream.next(m.fog_lights_on_is_valid);
      stream.next(m.headlights_mode);
      stream.next(m.headlights_mode_is_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HeadlightAuxRpt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::HeadlightAuxRpt_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "headlights_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.headlights_on);
    s << indent << "headlights_on_is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.headlights_on_is_valid);
    s << indent << "headlights_on_bright: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.headlights_on_bright);
    s << indent << "headlights_on_bright_is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.headlights_on_bright_is_valid);
    s << indent << "fog_lights_on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fog_lights_on);
    s << indent << "fog_lights_on_is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fog_lights_on_is_valid);
    s << indent << "headlights_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.headlights_mode);
    s << indent << "headlights_mode_is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.headlights_mode_is_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_HEADLIGHTAUXRPT_H
