// Generated by gencpp from file pacmod_msgs/LatLonHeadingRpt.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_LATLONHEADINGRPT_H
#define PACMOD_MSGS_MESSAGE_LATLONHEADINGRPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pacmod_msgs
{
template <class ContainerAllocator>
struct LatLonHeadingRpt_
{
  typedef LatLonHeadingRpt_<ContainerAllocator> Type;

  LatLonHeadingRpt_()
    : header()
    , latitude_degrees(0)
    , latitude_minutes(0)
    , latitude_seconds(0)
    , longitude_degrees(0)
    , longitude_minutes(0)
    , longitude_seconds(0)
    , heading(0.0)  {
    }
  LatLonHeadingRpt_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude_degrees(0)
    , latitude_minutes(0)
    , latitude_seconds(0)
    , longitude_degrees(0)
    , longitude_minutes(0)
    , longitude_seconds(0)
    , heading(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _latitude_degrees_type;
  _latitude_degrees_type latitude_degrees;

   typedef uint8_t _latitude_minutes_type;
  _latitude_minutes_type latitude_minutes;

   typedef uint8_t _latitude_seconds_type;
  _latitude_seconds_type latitude_seconds;

   typedef int8_t _longitude_degrees_type;
  _longitude_degrees_type longitude_degrees;

   typedef uint8_t _longitude_minutes_type;
  _longitude_minutes_type longitude_minutes;

   typedef uint8_t _longitude_seconds_type;
  _longitude_seconds_type longitude_seconds;

   typedef double _heading_type;
  _heading_type heading;





  typedef boost::shared_ptr< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> const> ConstPtr;

}; // struct LatLonHeadingRpt_

typedef ::pacmod_msgs::LatLonHeadingRpt_<std::allocator<void> > LatLonHeadingRpt;

typedef boost::shared_ptr< ::pacmod_msgs::LatLonHeadingRpt > LatLonHeadingRptPtr;
typedef boost::shared_ptr< ::pacmod_msgs::LatLonHeadingRpt const> LatLonHeadingRptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pacmod_msgs': ['/tmp/binarydeb/ros-kinetic-pacmod-msgs-3.0.1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "137a7c22b052c703f38a29aa79de4e50";
  }

  static const char* value(const ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x137a7c22b052c703ULL;
  static const uint64_t static_value2 = 0xf38a29aa79de4e50ULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/LatLonHeadingRpt";
  }

  static const char* value(const ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
int8 latitude_degrees\n\
uint8 latitude_minutes\n\
uint8 latitude_seconds\n\
int8 longitude_degrees\n\
uint8 longitude_minutes\n\
uint8 longitude_seconds\n\
float64 heading\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude_degrees);
      stream.next(m.latitude_minutes);
      stream.next(m.latitude_seconds);
      stream.next(m.longitude_degrees);
      stream.next(m.longitude_minutes);
      stream.next(m.longitude_seconds);
      stream.next(m.heading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LatLonHeadingRpt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::LatLonHeadingRpt_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude_degrees: ";
    Printer<int8_t>::stream(s, indent + "  ", v.latitude_degrees);
    s << indent << "latitude_minutes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.latitude_minutes);
    s << indent << "latitude_seconds: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.latitude_seconds);
    s << indent << "longitude_degrees: ";
    Printer<int8_t>::stream(s, indent + "  ", v.longitude_degrees);
    s << indent << "longitude_minutes: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.longitude_minutes);
    s << indent << "longitude_seconds: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.longitude_seconds);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_LATLONHEADINGRPT_H
