// Generated by gencpp from file pacmod_msgs/ShiftAuxRpt.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_SHIFTAUXRPT_H
#define PACMOD_MSGS_MESSAGE_SHIFTAUXRPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pacmod_msgs
{
template <class ContainerAllocator>
struct ShiftAuxRpt_
{
  typedef ShiftAuxRpt_<ContainerAllocator> Type;

  ShiftAuxRpt_()
    : header()
    , between_gears(false)
    , between_gears_is_valid(false)
    , stay_in_neutral_mode(false)
    , stay_in_neutral_mode_is_valid(false)
    , brake_interlock_active(false)
    , brake_interlock_active_is_valid(false)
    , speed_interlock_active(false)
    , speed_interlock_active_is_valid(false)
    , gear_number_avail(false)
    , gear_number(0)  {
    }
  ShiftAuxRpt_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , between_gears(false)
    , between_gears_is_valid(false)
    , stay_in_neutral_mode(false)
    , stay_in_neutral_mode_is_valid(false)
    , brake_interlock_active(false)
    , brake_interlock_active_is_valid(false)
    , speed_interlock_active(false)
    , speed_interlock_active_is_valid(false)
    , gear_number_avail(false)
    , gear_number(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _between_gears_type;
  _between_gears_type between_gears;

   typedef uint8_t _between_gears_is_valid_type;
  _between_gears_is_valid_type between_gears_is_valid;

   typedef uint8_t _stay_in_neutral_mode_type;
  _stay_in_neutral_mode_type stay_in_neutral_mode;

   typedef uint8_t _stay_in_neutral_mode_is_valid_type;
  _stay_in_neutral_mode_is_valid_type stay_in_neutral_mode_is_valid;

   typedef uint8_t _brake_interlock_active_type;
  _brake_interlock_active_type brake_interlock_active;

   typedef uint8_t _brake_interlock_active_is_valid_type;
  _brake_interlock_active_is_valid_type brake_interlock_active_is_valid;

   typedef uint8_t _speed_interlock_active_type;
  _speed_interlock_active_type speed_interlock_active;

   typedef uint8_t _speed_interlock_active_is_valid_type;
  _speed_interlock_active_is_valid_type speed_interlock_active_is_valid;

   typedef uint8_t _gear_number_avail_type;
  _gear_number_avail_type gear_number_avail;

   typedef int8_t _gear_number_type;
  _gear_number_type gear_number;





  typedef boost::shared_ptr< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> const> ConstPtr;

}; // struct ShiftAuxRpt_

typedef ::pacmod_msgs::ShiftAuxRpt_<std::allocator<void> > ShiftAuxRpt;

typedef boost::shared_ptr< ::pacmod_msgs::ShiftAuxRpt > ShiftAuxRptPtr;
typedef boost::shared_ptr< ::pacmod_msgs::ShiftAuxRpt const> ShiftAuxRptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pacmod_msgs': ['/tmp/binarydeb/ros-kinetic-pacmod-msgs-3.0.1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd3dcb724fff7aa8174cd1060347a710";
  }

  static const char* value(const ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd3dcb724fff7aa8ULL;
  static const uint64_t static_value2 = 0x174cd1060347a710ULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/ShiftAuxRpt";
  }

  static const char* value(const ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
bool between_gears\n\
bool between_gears_is_valid\n\
bool stay_in_neutral_mode\n\
bool stay_in_neutral_mode_is_valid\n\
bool brake_interlock_active\n\
bool brake_interlock_active_is_valid\n\
bool speed_interlock_active\n\
bool speed_interlock_active_is_valid\n\
bool gear_number_avail\n\
int8 gear_number\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.between_gears);
      stream.next(m.between_gears_is_valid);
      stream.next(m.stay_in_neutral_mode);
      stream.next(m.stay_in_neutral_mode_is_valid);
      stream.next(m.brake_interlock_active);
      stream.next(m.brake_interlock_active_is_valid);
      stream.next(m.speed_interlock_active);
      stream.next(m.speed_interlock_active_is_valid);
      stream.next(m.gear_number_avail);
      stream.next(m.gear_number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShiftAuxRpt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::ShiftAuxRpt_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "between_gears: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.between_gears);
    s << indent << "between_gears_is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.between_gears_is_valid);
    s << indent << "stay_in_neutral_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stay_in_neutral_mode);
    s << indent << "stay_in_neutral_mode_is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.stay_in_neutral_mode_is_valid);
    s << indent << "brake_interlock_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_interlock_active);
    s << indent << "brake_interlock_active_is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brake_interlock_active_is_valid);
    s << indent << "speed_interlock_active: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed_interlock_active);
    s << indent << "speed_interlock_active_is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.speed_interlock_active_is_valid);
    s << indent << "gear_number_avail: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gear_number_avail);
    s << indent << "gear_number: ";
    Printer<int8_t>::stream(s, indent + "  ", v.gear_number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_SHIFTAUXRPT_H
