// Generated by gencpp from file pacmod_msgs/VehicleDynamicsRpt.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_VEHICLEDYNAMICSRPT_H
#define PACMOD_MSGS_MESSAGE_VEHICLEDYNAMICSRPT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pacmod_msgs
{
template <class ContainerAllocator>
struct VehicleDynamicsRpt_
{
  typedef VehicleDynamicsRpt_<ContainerAllocator> Type;

  VehicleDynamicsRpt_()
    : header()
    , brake_torque(0.0)
    , g_forces(0)  {
    }
  VehicleDynamicsRpt_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , brake_torque(0.0)
    , g_forces(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _brake_torque_type;
  _brake_torque_type brake_torque;

   typedef uint8_t _g_forces_type;
  _g_forces_type g_forces;





  typedef boost::shared_ptr< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleDynamicsRpt_

typedef ::pacmod_msgs::VehicleDynamicsRpt_<std::allocator<void> > VehicleDynamicsRpt;

typedef boost::shared_ptr< ::pacmod_msgs::VehicleDynamicsRpt > VehicleDynamicsRptPtr;
typedef boost::shared_ptr< ::pacmod_msgs::VehicleDynamicsRpt const> VehicleDynamicsRptConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pacmod_msgs': ['/tmp/binarydeb/ros-kinetic-pacmod-msgs-3.0.1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "76c5ee0fb5b1065da372a973e2ffdd31";
  }

  static const char* value(const ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x76c5ee0fb5b1065dULL;
  static const uint64_t static_value2 = 0xa372a973e2ffdd31ULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/VehicleDynamicsRpt";
  }

  static const char* value(const ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
float64 brake_torque       # Measured brake torque\n\
uint8 g_forces             # Measured g forces\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.brake_torque);
      stream.next(m.g_forces);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleDynamicsRpt_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::VehicleDynamicsRpt_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "brake_torque: ";
    Printer<double>::stream(s, indent + "  ", v.brake_torque);
    s << indent << "g_forces: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.g_forces);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_VEHICLEDYNAMICSRPT_H
