// Generated by gencpp from file pacmod_msgs/VehicleSpecificRpt1.msg
// DO NOT EDIT!


#ifndef PACMOD_MSGS_MESSAGE_VEHICLESPECIFICRPT1_H
#define PACMOD_MSGS_MESSAGE_VEHICLESPECIFICRPT1_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace pacmod_msgs
{
template <class ContainerAllocator>
struct VehicleSpecificRpt1_
{
  typedef VehicleSpecificRpt1_<ContainerAllocator> Type;

  VehicleSpecificRpt1_()
    : header()
    , shift_pos_1(0)
    , shift_pos_2(0)  {
    }
  VehicleSpecificRpt1_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , shift_pos_1(0)
    , shift_pos_2(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _shift_pos_1_type;
  _shift_pos_1_type shift_pos_1;

   typedef uint8_t _shift_pos_2_type;
  _shift_pos_2_type shift_pos_2;





  typedef boost::shared_ptr< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> const> ConstPtr;

}; // struct VehicleSpecificRpt1_

typedef ::pacmod_msgs::VehicleSpecificRpt1_<std::allocator<void> > VehicleSpecificRpt1;

typedef boost::shared_ptr< ::pacmod_msgs::VehicleSpecificRpt1 > VehicleSpecificRpt1Ptr;
typedef boost::shared_ptr< ::pacmod_msgs::VehicleSpecificRpt1 const> VehicleSpecificRpt1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pacmod_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pacmod_msgs': ['/tmp/binarydeb/ros-kinetic-pacmod-msgs-3.0.1/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e61481747bb1386c6b9f8ef5c5adad62";
  }

  static const char* value(const ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe61481747bb1386cULL;
  static const uint64_t static_value2 = 0x6b9f8ef5c5adad62ULL;
};

template<class ContainerAllocator>
struct DataType< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pacmod_msgs/VehicleSpecificRpt1";
  }

  static const char* value(const ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
\n\
uint8 shift_pos_1\n\
uint8 shift_pos_2\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.shift_pos_1);
      stream.next(m.shift_pos_2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VehicleSpecificRpt1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pacmod_msgs::VehicleSpecificRpt1_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "shift_pos_1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shift_pos_1);
    s << indent << "shift_pos_2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.shift_pos_2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PACMOD_MSGS_MESSAGE_VEHICLESPECIFICRPT1_H
