// Generated by gencpp from file spatio_temporal_voxel_layer/SaveGridRequest.msg
// DO NOT EDIT!


#ifndef SPATIO_TEMPORAL_VOXEL_LAYER_MESSAGE_SAVEGRIDREQUEST_H
#define SPATIO_TEMPORAL_VOXEL_LAYER_MESSAGE_SAVEGRIDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/String.h>

namespace spatio_temporal_voxel_layer
{
template <class ContainerAllocator>
struct SaveGridRequest_
{
  typedef SaveGridRequest_<ContainerAllocator> Type;

  SaveGridRequest_()
    : file_name()  {
    }
  SaveGridRequest_(const ContainerAllocator& _alloc)
    : file_name(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::String_<ContainerAllocator>  _file_name_type;
  _file_name_type file_name;





  typedef boost::shared_ptr< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SaveGridRequest_

typedef ::spatio_temporal_voxel_layer::SaveGridRequest_<std::allocator<void> > SaveGridRequest;

typedef boost::shared_ptr< ::spatio_temporal_voxel_layer::SaveGridRequest > SaveGridRequestPtr;
typedef boost::shared_ptr< ::spatio_temporal_voxel_layer::SaveGridRequest const> SaveGridRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spatio_temporal_voxel_layer

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'dynamic_reconfigure': ['/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f46a7b91c582f33b0ff0851cd14eed20";
  }

  static const char* value(const ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf46a7b91c582f33bULL;
  static const uint64_t static_value2 = 0x0ff0851cd14eed20ULL;
};

template<class ContainerAllocator>
struct DataType< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spatio_temporal_voxel_layer/SaveGridRequest";
  }

  static const char* value(const ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/String file_name\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/String\n\
string data\n\
";
  }

  static const char* value(const ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.file_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SaveGridRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spatio_temporal_voxel_layer::SaveGridRequest_<ContainerAllocator>& v)
  {
    s << indent << "file_name: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.file_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPATIO_TEMPORAL_VOXEL_LAYER_MESSAGE_SAVEGRIDREQUEST_H
