// Generated by gencpp from file rosapi/TopicsAndRawTypes.msg
// DO NOT EDIT!


#ifndef ROSAPI_MESSAGE_TOPICSANDRAWTYPES_H
#define ROSAPI_MESSAGE_TOPICSANDRAWTYPES_H

#include <ros/service_traits.h>


#include <rosapi/TopicsAndRawTypesRequest.h>
#include <rosapi/TopicsAndRawTypesResponse.h>


namespace rosapi
{

struct TopicsAndRawTypes
{

typedef TopicsAndRawTypesRequest Request;
typedef TopicsAndRawTypesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TopicsAndRawTypes
} // namespace rosapi


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rosapi::TopicsAndRawTypes > {
  static const char* value()
  {
    return "e1432466c8f64316723276ba07c59d12";
  }

  static const char* value(const ::rosapi::TopicsAndRawTypes&) { return value(); }
};

template<>
struct DataType< ::rosapi::TopicsAndRawTypes > {
  static const char* value()
  {
    return "rosapi/TopicsAndRawTypes";
  }

  static const char* value(const ::rosapi::TopicsAndRawTypes&) { return value(); }
};


// service_traits::MD5Sum< ::rosapi::TopicsAndRawTypesRequest> should match 
// service_traits::MD5Sum< ::rosapi::TopicsAndRawTypes > 
template<>
struct MD5Sum< ::rosapi::TopicsAndRawTypesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::TopicsAndRawTypes >::value();
  }
  static const char* value(const ::rosapi::TopicsAndRawTypesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::TopicsAndRawTypesRequest> should match 
// service_traits::DataType< ::rosapi::TopicsAndRawTypes > 
template<>
struct DataType< ::rosapi::TopicsAndRawTypesRequest>
{
  static const char* value()
  {
    return DataType< ::rosapi::TopicsAndRawTypes >::value();
  }
  static const char* value(const ::rosapi::TopicsAndRawTypesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rosapi::TopicsAndRawTypesResponse> should match 
// service_traits::MD5Sum< ::rosapi::TopicsAndRawTypes > 
template<>
struct MD5Sum< ::rosapi::TopicsAndRawTypesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rosapi::TopicsAndRawTypes >::value();
  }
  static const char* value(const ::rosapi::TopicsAndRawTypesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rosapi::TopicsAndRawTypesResponse> should match 
// service_traits::DataType< ::rosapi::TopicsAndRawTypes > 
template<>
struct DataType< ::rosapi::TopicsAndRawTypesResponse>
{
  static const char* value()
  {
    return DataType< ::rosapi::TopicsAndRawTypes >::value();
  }
  static const char* value(const ::rosapi::TopicsAndRawTypesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROSAPI_MESSAGE_TOPICSANDRAWTYPES_H
