// Generated by gencpp from file jsk_recognition_msgs/CheckCollision.msg
// DO NOT EDIT!


#ifndef JSK_RECOGNITION_MSGS_MESSAGE_CHECKCOLLISION_H
#define JSK_RECOGNITION_MSGS_MESSAGE_CHECKCOLLISION_H

#include <ros/service_traits.h>


#include <jsk_recognition_msgs/CheckCollisionRequest.h>
#include <jsk_recognition_msgs/CheckCollisionResponse.h>


namespace jsk_recognition_msgs
{

struct CheckCollision
{

typedef CheckCollisionRequest Request;
typedef CheckCollisionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CheckCollision
} // namespace jsk_recognition_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_recognition_msgs::CheckCollision > {
  static const char* value()
  {
    return "3a30746acfb91fe161523d1e16f11286";
  }

  static const char* value(const ::jsk_recognition_msgs::CheckCollision&) { return value(); }
};

template<>
struct DataType< ::jsk_recognition_msgs::CheckCollision > {
  static const char* value()
  {
    return "jsk_recognition_msgs/CheckCollision";
  }

  static const char* value(const ::jsk_recognition_msgs::CheckCollision&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_recognition_msgs::CheckCollisionRequest> should match 
// service_traits::MD5Sum< ::jsk_recognition_msgs::CheckCollision > 
template<>
struct MD5Sum< ::jsk_recognition_msgs::CheckCollisionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_recognition_msgs::CheckCollision >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::CheckCollisionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_recognition_msgs::CheckCollisionRequest> should match 
// service_traits::DataType< ::jsk_recognition_msgs::CheckCollision > 
template<>
struct DataType< ::jsk_recognition_msgs::CheckCollisionRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_recognition_msgs::CheckCollision >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::CheckCollisionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_recognition_msgs::CheckCollisionResponse> should match 
// service_traits::MD5Sum< ::jsk_recognition_msgs::CheckCollision > 
template<>
struct MD5Sum< ::jsk_recognition_msgs::CheckCollisionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_recognition_msgs::CheckCollision >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::CheckCollisionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_recognition_msgs::CheckCollisionResponse> should match 
// service_traits::DataType< ::jsk_recognition_msgs::CheckCollision > 
template<>
struct DataType< ::jsk_recognition_msgs::CheckCollisionResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_recognition_msgs::CheckCollision >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::CheckCollisionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_RECOGNITION_MSGS_MESSAGE_CHECKCOLLISION_H
