// Generated by gencpp from file jsk_recognition_msgs/EuclideanSegment.msg
// DO NOT EDIT!


#ifndef JSK_RECOGNITION_MSGS_MESSAGE_EUCLIDEANSEGMENT_H
#define JSK_RECOGNITION_MSGS_MESSAGE_EUCLIDEANSEGMENT_H

#include <ros/service_traits.h>


#include <jsk_recognition_msgs/EuclideanSegmentRequest.h>
#include <jsk_recognition_msgs/EuclideanSegmentResponse.h>


namespace jsk_recognition_msgs
{

struct EuclideanSegment
{

typedef EuclideanSegmentRequest Request;
typedef EuclideanSegmentResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EuclideanSegment
} // namespace jsk_recognition_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_recognition_msgs::EuclideanSegment > {
  static const char* value()
  {
    return "7210bbdf9078b61fce51942a9f673096";
  }

  static const char* value(const ::jsk_recognition_msgs::EuclideanSegment&) { return value(); }
};

template<>
struct DataType< ::jsk_recognition_msgs::EuclideanSegment > {
  static const char* value()
  {
    return "jsk_recognition_msgs/EuclideanSegment";
  }

  static const char* value(const ::jsk_recognition_msgs::EuclideanSegment&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_recognition_msgs::EuclideanSegmentRequest> should match 
// service_traits::MD5Sum< ::jsk_recognition_msgs::EuclideanSegment > 
template<>
struct MD5Sum< ::jsk_recognition_msgs::EuclideanSegmentRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_recognition_msgs::EuclideanSegment >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::EuclideanSegmentRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_recognition_msgs::EuclideanSegmentRequest> should match 
// service_traits::DataType< ::jsk_recognition_msgs::EuclideanSegment > 
template<>
struct DataType< ::jsk_recognition_msgs::EuclideanSegmentRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_recognition_msgs::EuclideanSegment >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::EuclideanSegmentRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_recognition_msgs::EuclideanSegmentResponse> should match 
// service_traits::MD5Sum< ::jsk_recognition_msgs::EuclideanSegment > 
template<>
struct MD5Sum< ::jsk_recognition_msgs::EuclideanSegmentResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_recognition_msgs::EuclideanSegment >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::EuclideanSegmentResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_recognition_msgs::EuclideanSegmentResponse> should match 
// service_traits::DataType< ::jsk_recognition_msgs::EuclideanSegment > 
template<>
struct DataType< ::jsk_recognition_msgs::EuclideanSegmentResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_recognition_msgs::EuclideanSegment >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::EuclideanSegmentResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_RECOGNITION_MSGS_MESSAGE_EUCLIDEANSEGMENT_H
