// Generated by gencpp from file jsk_recognition_msgs/SaveMesh.msg
// DO NOT EDIT!


#ifndef JSK_RECOGNITION_MSGS_MESSAGE_SAVEMESH_H
#define JSK_RECOGNITION_MSGS_MESSAGE_SAVEMESH_H

#include <ros/service_traits.h>


#include <jsk_recognition_msgs/SaveMeshRequest.h>
#include <jsk_recognition_msgs/SaveMeshResponse.h>


namespace jsk_recognition_msgs
{

struct SaveMesh
{

typedef SaveMeshRequest Request;
typedef SaveMeshResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMesh
} // namespace jsk_recognition_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::jsk_recognition_msgs::SaveMesh > {
  static const char* value()
  {
    return "bac972d77fa349fd55cd1ee98f47a7b0";
  }

  static const char* value(const ::jsk_recognition_msgs::SaveMesh&) { return value(); }
};

template<>
struct DataType< ::jsk_recognition_msgs::SaveMesh > {
  static const char* value()
  {
    return "jsk_recognition_msgs/SaveMesh";
  }

  static const char* value(const ::jsk_recognition_msgs::SaveMesh&) { return value(); }
};


// service_traits::MD5Sum< ::jsk_recognition_msgs::SaveMeshRequest> should match 
// service_traits::MD5Sum< ::jsk_recognition_msgs::SaveMesh > 
template<>
struct MD5Sum< ::jsk_recognition_msgs::SaveMeshRequest>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_recognition_msgs::SaveMesh >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::SaveMeshRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_recognition_msgs::SaveMeshRequest> should match 
// service_traits::DataType< ::jsk_recognition_msgs::SaveMesh > 
template<>
struct DataType< ::jsk_recognition_msgs::SaveMeshRequest>
{
  static const char* value()
  {
    return DataType< ::jsk_recognition_msgs::SaveMesh >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::SaveMeshRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::jsk_recognition_msgs::SaveMeshResponse> should match 
// service_traits::MD5Sum< ::jsk_recognition_msgs::SaveMesh > 
template<>
struct MD5Sum< ::jsk_recognition_msgs::SaveMeshResponse>
{
  static const char* value()
  {
    return MD5Sum< ::jsk_recognition_msgs::SaveMesh >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::SaveMeshResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::jsk_recognition_msgs::SaveMeshResponse> should match 
// service_traits::DataType< ::jsk_recognition_msgs::SaveMesh > 
template<>
struct DataType< ::jsk_recognition_msgs::SaveMeshResponse>
{
  static const char* value()
  {
    return DataType< ::jsk_recognition_msgs::SaveMesh >::value();
  }
  static const char* value(const ::jsk_recognition_msgs::SaveMeshResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // JSK_RECOGNITION_MSGS_MESSAGE_SAVEMESH_H
